### ISSUE TITLE
Crash when opening an EXCEL file

### ISSUE THREAD

**Issue by k7sleeper** [gutkyu/node-xlrd#1]
Running the example code for my own EXCEL table (.xls file) I get the following exception:

```
D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\sheet.js:1055
                var txo = self.handle_txo(data);
                               ^

TypeError: self.handle_txo is not a function
  at Sheet.self.read (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\sheet.js:1055:32)
  at getSheet (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\workbook.js:500:6)
  at D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\workbook.js:511:4
  at Array.forEach (native)
  at Object.getSheets (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\workbook.js:509:15)
  at Object.exports.openWorkbook (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\workbook.js:52:31)
  at D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\node-xlrd\lib\node-xlrd.js:31:15
  at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
```

**Comment by gutkyu** [comment]
would you send your excel file to my email?

**Comment by OscarJun** [comment]
Did you solve the problem? I met the similar problem
